# Generated by Django 3.1.3 on 2020-12-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
