# Generated by Django 3.1.3 on 2020-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('user_profile', '0002_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
